### ISSUE TITLE
Add Teamviewer 11 support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#126]
It's seems that Teamviewer 11 have a tray icon now. I think it's a Qt icon; 
but i can use it in Fedora 23,  i don't know why.
@wa4557 @Foggalong Any one of you is using Ubuntu or XFCE to help me get the icon name ? :+1:

**Comment by wa4557** [comment]
No icons in `/tmp`. I don't think it's a QT application

**Comment by bil-elmoussaoui** [comment]
It's Qt wine application..The only icon installed by the application is in `/opt/teamviewer/tv_bin/desktop/` can you confirm that?

**Comment by bil-elmoussaoui** [comment]
And in this folder `opt/teamviewer/tv_bin/RTlib/plugins/systemtrayicon` you can find the plugin for the tray icon. I looked at the code,  and application do create a folder in /tmp for Qt icons

**Comment by wa4557** [comment]
This: `opt/teamviewer/tv_bin/RTlib/plugins/systemtrayicon` does not exist on my machine. And no there is nothing in `/tmp`

**Comment by bil-elmoussaoui** [comment]
In my case i have this folder `sni-qt_TVGuiDelegate_10300-0nRVI4`But there's nothing in the `icons` folder :/ I tried changing the icon in `/opt/teamviewer/tv_bin/desktop/` but that does not change the icon too. I think that the icon is hardcoded in the binary file..

**Comment by wa4557** [comment]
Yeah I don't have that folder :( Changing the icon doesn't help in my case either...

**Comment by bil-elmoussaoui** [comment]
Will keep it open, maybe something will change later..

**Comment by wa4557** [comment]
Ok my fault I wa still having teamviewer 10 installed. For teamviewer 11 I have those icons in `/tmp`
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/11912787/bca636cc-a64d-11e5-912a-707c88ca496e.png)

```
TVGuiDelegate_30638_0b040b0d9ec00ce0d8189ece93cd2b7f.png
TVGuiDelegate_30638_4327113cab136a09fac832e66878159a.png
TVGuiDelegate_30638_54b99333baa6a26fda3eb8ce6d664bd5.png
```

**Comment by bil-elmoussaoui** [comment]
Haha:P 
What do you think about those names?
```csv
0b040b0d9ec00ce0d8189ece93cd2b7f.png, teamviewer-indicator, qt-tray
54b99333baa6a26fda3eb8ce6d664bd5.png, teamviewer-indicator-error, qt-tray
4327113cab136a09fac832e66878159a.png, teamviewer-indicator-connected qt-tray
```

**Comment by wa4557** [comment]
:1:

**Comment by bil-elmoussaoui** [comment]
Fixed in 2ca7031b0a2c63a504ba59c52908737a60c259d0
Thanks :+1:

**Comment by wa4557** [comment]
Can you post the output of the code for the trayicon-lugin (maybe pastebin)? (opt/teamviewer/tv_bin/RTlib/plugins/systemtrayico) Still does not exist  on my machine, and I'm trying to find out the name of the plugin, to put it in the right position on the tray...

**Comment by bil-elmoussaoui** [comment]
You can download the deb file from the website, and extract it you will find the file, i can't copy/paste the content file as it's `.so` file.. :/

**Comment by wa4557** [comment]
And how to look at the code then?

**Comment by bil-elmoussaoui** [comment]
You will need to use a Hex editor :s (Bless Hex Editor is a good one!)

**Comment by wa4557** [comment]
Ah yeah sure. Thx :)

**Comment by wa4557** [comment]
There is another icon... `TVGuiDelegate_28264_c28d37df9872311f7c6b295b70b8a39d`

![unbenannt](https://cloud.githubusercontent.com/assets/6475757/11918357/e1e2aa20-a72d-11e5-8ccd-20dbdc1d9ed2.png)

**Comment by bil-elmoussaoui** [comment]
Added as `teamviewer-indicator-paused`, but i don't know if it's the right name; when this icon is being used?

**Comment by wa4557** [comment]
I guess `idle` would be better or `away` or `inactive`

**Comment by bil-elmoussaoui** [comment]
changed that to `idle` :+1:

**Comment by wa4557** [comment]
Designing those icon will be hard :/

**Comment by bil-elmoussaoui** [comment]
Like a lot of status icons.. As nobody is using them, there's no reason to include them in Numix base theme ;)

**Comment by bil-elmoussaoui** [comment]
#91 are the hardest ones to do !

**Comment by wa4557** [comment]
Well I am using them, so I have an interest in adding them + teamviewer is actually a program widely used :)

**Comment by bil-elmoussaoui** [comment]
You can use only the double arrow as a base icon ?

**Comment by wa4557** [comment]
Oh come one...
```
TVGuiDelegate_28264_0b040b0d9ec00ce0d8189ece93cd2b7f.png
TVGuiDelegate_28264_4327113cab136a09fac832e66878159a.png
TVGuiDelegate_28264_4cd9545d0021db224685d863ac738f91.png
TVGuiDelegate_28264_54b99333baa6a26fda3eb8ce6d664bd5.png
TVGuiDelegate_28264_86e4f5bf63a6fa1725afd2e08e0ce105.png
TVGuiDelegate_28264_c28d37df9872311f7c6b295b70b8a39d.png
```

![unbenannt](https://cloud.githubusercontent.com/assets/6475757/11918416/982f65f0-a730-11e5-91df-ac134476d094.png)

**Comment by bil-elmoussaoui** [comment]
Added them too :P https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/database/teamviewer Just don't know how to name the two new icons, can you do that?

**Comment by wa4557** [comment]
Done

**Comment by bil-elmoussaoui** [comment]
Thanks , i've opened a new request in Numix base repo ;)
