### ISSUE TITLE
Messenger support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#157]
Messenger for desktop is a nodejs wrapper for Facebook messenger https://github.com/Aluxian/Facebook-Messenger-Desktop

The icon is mustly hardcoded on the binary file i guess..

**Comment by wa4557** [comment]
Is this app released yet? (Haven't found a deb to figure out where to look)

**Comment by bil-elmoussaoui** [comment]
There's a deb file here https://messengerfordesktop.com/

**Comment by wa4557** [comment]
Seems to be the same as with Gitter. No idea how to fix that (yet)

**Comment by bil-elmoussaoui** [comment]
All the nw.js applications have a `icudtl.dat` file. Maybe we should see if we can extract it ?

**Comment by wa4557** [comment]
That's a chromium specific file, I don't think that the icons are stored in there...

**Comment by bil-elmoussaoui** [comment]
I've found a way to theme nw.js application; i will create a PR soon

**Comment by bil-elmoussaoui** [comment]
Well, i have a few issues with that. The icons and all the files informations are stored in the executable file. Which is a normal zip file that you can extract. The first issue is that the extracted folder does not have the same size as the executable file at all...
But all we have to do is 
- Extract the binary file (zip file)
- Change the icons
- Zip the file again  https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps#linux--os-x
- Convert the zipped `.nw` file to an executable one https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps#linux

**Comment by wa4557** [comment]
Do we have to really extract that or is it possible to do it like with the spotify icon?

**Comment by bil-elmoussaoui** [comment]
I don't know if it's possible to modify the file directly, didn't try it yet

**Comment by wa4557** [comment]
I had a look into this, and I was able to succesfully replace the icons for FacebookMessenger. 
Steps

1) Extract the binary file: `unzip Messenger`
2) change icons
3) `zip -r ../${PWD##*/}.nw *`
4) `mv Messenger.nw Messenger`
5) `chmod +x Messenger`

It would still be better to do this without extracting the whole file

**Comment by bil-elmoussaoui** [comment]
If it's just a zip file we can change the icons directly nop? btw, there's a nwjs branch if you want to work on this

**Comment by wa4557** [comment]
I'm working on this, let's see if I figure out the best way to do it :)

**Comment by wa4557** [comment]
I have a semi-working version uploaded to the nwjs branch. It doesn't work without unpacking and repacking again though :( Maybe you can try, there is still an issue with `chmod` but apart from that it should work

**Comment by bil-elmoussaoui** [comment]
It's not working here 
I'm getting this error 
```bash
fixing failed with error:
	Traceback (most recent call last):
	  File "/home/bilal/Téléchargements/Hardcode-Tray/database/scripts/nwjs", line 52, in <module>
	    update_zip(icon_to_repl, filename, pngbytes)
	  File "/home/bilal/Téléchargements/Hardcode-Tray/database/scripts/nwjs", line 11, in update_zip
	    zin = zipfile.ZipFile(filename, 'r')
	  File "/usr/lib/python3.5/zipfile.py", line 1009, in __init__
	    self.fp = io.open(file, filemode)
	FileNotFoundError: [Errno 2] No such file or directory: '/opt/MessengerForDesktop/Messenger'
```
I think the issue is due to the name of the file, when i took a look at `/opt/MessengerForDesktop` the only file i found was `Messenger.zip`
For the permission issue, you only need to execute `chmod +x nwjs` and it should be okay (tried it, and it works finne)

**Comment by wa4557** [comment]
Yeah but then the database file is wrong and should read `Messenger.zip` instead of `Messenger`.

**Comment by bil-elmoussaoui** [comment]
Are you sure about this? Because the script won't find Messenger.zip file during the first icon fix.. 
I think we can fix this by renaming the script back after we modify the zip file

**Comment by wa4557** [comment]
Well the error message says: `FileNotFoundError: [Errno 2] No such file or directory: '/opt/MessengerForDesktop/Messenger'` this means that this file does not exist, right?

**Comment by wa4557** [comment]
For Gitter this doesn't work btw., I think I need to come up with a better way to do this...

**Comment by bil-elmoussaoui** [comment]
Yeah but the error is shown after the first icon is fixed

**Comment by wa4557** [comment]
Ah I think we have to to chmod after each icon that is fixed, noone has read access to the fle, after the fixing occured. Still not extremely happy with the solution anyways, have to think about this a bit

**Comment by bil-elmoussaoui** [comment]
Alright, btw the latest version of MessengerForDesktop is using Electron :P so the only reason to add nwjs support is Gitter :(

**Comment by wa4557** [comment]
what if we just don't support them? I mean it is definitely doable in principle, but I really don't like this solution of unpacking it to the harddisc each time we fix an icon.

**Comment by bil-elmoussaoui** [comment]
We can do that, but there's still some people using nwjs apps out there... I prefer to keep this open until we got a better solution to fix this!

**Comment by wa4557** [comment]
I think I found a better way to handle nw.js files. https://github.com/wa4557/Hardcode-Tray/commit/e8668adc42578e1d980d6fba2cea2cce0deafb54 

No python magic necessary there, just a temporary folder in the /tmp/ directory. I guess that is fine?

**Comment by bil-elmoussaoui** [comment]
Looks fine for me ! We don't need to implement the fastest solution as nwjs is almost dead, everyone is using Electron right now :+1:  
Can you keep the two other applications i've added to nwjs branch?

**Comment by wa4557** [comment]
I kind of fucked up the branch so we might have to readd everything. Just realized that this does not work with gitter though :( Works with facebook messenger, ah what the heck

**Comment by bil-elmoussaoui** [comment]
Are you using the latest version of Gitter?

**Comment by wa4557** [comment]
Yeah downloaded the deb file from their homepage

**Comment by bil-elmoussaoui** [comment]
Can you try it with Popcorntime-CE ? i guess that Gitter might be applying some verification the same way chrome does with its extensions...

**Comment by wa4557** [comment]
I don't even have a tray icon with Popcorn Time

**Comment by bil-elmoussaoui** [comment]
I tried the latest version you pushed on your fork and i have some feedback:
- I don't think that using a counter in order to know if we have to unzip/zip the file, this causes an issue when only one icon is supported for example. The file won't be extracted into /tmp and nothing will work as expected :P the only way i can think of in order to avoid this is to unzip the file at the beginning and zip it back at the end of each icon change. A better idea is to restructure the script which will take much more time, and instead of checking each icon, we do that at the beginning and create a dict with all the applications with sub-dict of each icon supported by the theme (don't know if it's clear :P) 
- There's an issue when packing the zip file back 
```bash
	warning [/usr/share/popcorntime-ce/Popcorn-Time-CE]:  74723616 extra bytes at beginning or within zipfile
	  (attempting to process anyway)
```

**Comment by wa4557** [comment]
Didnt think about the single icon case. This can be solved fairly easy though. 

Concerning zipping unzipping yeah I saw that too did not figure Out whats causing this yet. Did the replacement work?

**Comment by wa4557** [comment]
Restructuring the Script is definitely a good idea we could gain a lot of Speed doung this (in General)

**Comment by bil-elmoussaoui** [comment]
I will work on restructuring the script, this will help me fix #170 as i needed a list of the icons that are going to be fixed by hardcode-tray but wasn't possible with changing too many lines :/
Will push a new version of the script with a fix of #184 too, after that we can investigate how to fix nwjs issue!

**Comment by wa4557** [comment]
What I don't get: We're already doing this right? There is the function `get_apps_information` that throws everything together into a big dictionary, why is necessary to restructure the script then?

**Comment by bil-elmoussaoui** [comment]
That's correct, but the issue is the `get_apps_information` will only check if the applications are installed or not. We do the rest of the job on `install` and we check if the icons do exists or not. What i'm thinking of is moving the part where we check if the icons do exists into an other function that will be called in `get_apps_icons` (don't remember the function name). This way the list of icons that will be returned to `get_apps_information` will have only supported apps with existing icons on your default theme.

**Comment by wa4557** [comment]
Have youbalready started working on that? I guess it should be very easy. I can do if you want

**Comment by bil-elmoussaoui** [comment]
Yes it should be ready in an hour i guess :) i'm trying to re-read the code and improve it too!

**Comment by wa4557** [comment]
I fixed the nwjs script and adapted the script accordingly. Should also work if there's only one icon to fix now.

https://github.com/bil-elmoussaoui/Hardcode-Tray/tree/nwjs2

**Comment by bil-elmoussaoui** [comment]
@wa4557 I tried your branch and i have few things to report back : 
1 - On line 600, you forgot to convert `script_do` to a string 
2 - Can you please apply `chmod +x nwjs` and push the changes to your branch?
3 - I tried it with Gitter, and i had this error message 
```bash
	Traceback (most recent call last):
	  File "svgtopng.py", line 65, in <module>
	    convert_svg2png(infile, outfile)
	  File "svgtopng.py", line 33, in convert_svg2png
	    fout = open(outfile, "wb")
	FileNotFoundError: [Errno 2] No such file or directory: '/tmp/Gitter/img/linux-icon-logo-connected.png'
	
	
```

**Comment by bil-elmoussaoui** [comment]
The third issue is happening because of this. I took the executable file after i ran hardcode-tray; and i extracted it's content, the content of the file was in `/Gitter/tmp/Gitter/` instead of just `/Gitter/`
But the icon is being replaced successfully!
One more issue is 
```bash
	warning [/opt/Gitter/linux64/Gitter]:  74723616 extra bytes at beginning or within zipfile
	  (attempting to process anyway)
``` 
I didn't tried to run Gitter again to see if it's working, i will do once the two other issues are fixed :P

**Comment by bil-elmoussaoui** [comment]
Fixed 1, 2 and 3 ! The only issue that i still have is the extra bytes at the beginning of the zipfile..

**Comment by bil-elmoussaoui** [comment]
I did some more tests, it seems that you will need nw installed on your system in order to package the nw file and make it executable again (see my latest commit). 
As an Arch user, i installed this package https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nwjs-bin (this is the PKGBUILD, might help you package it yourself)
You will need to copy `libnw.so` and `libffmpeg.so` that ships with nw to `/usr/lib` (the PKGBUILD file does not do that :( )
Once i've done all of that, i run Gitter, and i have this new error message
```bash
[1103/003028:FATAL:v8_initializer.cc(292)] Couldn't mmap v8 natives data file, status code is 1
/usr/bin/gitter : ligne 3 :  6755 Abandon                 (core dumped)LD_LIBRARY_PATH=/opt/Gitter/lib /opt/Gitter/linux64/Gitter $*
```

**Comment by bil-elmoussaoui** [comment]
I was able to get ride of all those errors, i took a look at some issues on nwjs repo and i figured out that i had to ship 
- nw_100_percent.pak
- nw_200_percent.pak
- resources.pak
- natives_blob.bin
- snapshot_blob.bin

Those files are from Chromium and so they are shipped with nwjs too!
Copying those files to the directory where you copy the executable nwjs file did the trick!
But the application is not being executed at all :(  The only thing that might causes this is the extra bytes issue

**Comment by bil-elmoussaoui** [comment]
I did some digging, repackaging the application is just impossible in to many ways. i was able to rebuilt the Gitter source file using nwbuilder. And it worked correctly, the only problem is that you need to specify the exact nwjs version otherwise it might not work as expected and also, it need to download the nwjs sdk (almost 70mb) which will make it so slow for users that have a slow internet connection! 
So either we figure out how to do this by just changing the files in the binary without even extracting it or we don't support nwjs apps at all....
@wa4557 what do you think?

**Comment by wa4557** [comment]
nwjs is dying anyways...

**Comment by bil-elmoussaoui** [comment]
I know, but i must use Gitter on my laptop and the tray icon was so ugly!

**Comment by wa4557** [comment]
Same with teamviewer here :) Maybe report it upstream to nwjs?

**Comment by bil-elmoussaoui** [comment]
Already fixed it on master :+1:

**Comment by wa4557** [comment]
Wut? How?

**Comment by bil-elmoussaoui** [comment]
See my comment on the gitter issue

**Comment by bil-elmoussaoui** [comment]
For more info:
The whole issue is that we were trying to run nw directly, which needed the whole nwjs sdk to make things work...

**Comment by wa4557** [comment]
ok, so I just need to download the sdk point to it in the config file and all nwjs issues are solved?

**Comment by bil-elmoussaoui** [comment]
Yep ! I will add more info on the readme file about that, and ofc it need some more testing before releasing it, but it works

**Comment by wa4557** [comment]
Cool
