### ISSUE TITLE
teamviewer doesn't work anymore

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#163]
I have absolutely no idea why, but teamviewer stopped working :( `libsniqt.so` is replaced correctly and also the icons in `/home/andreas/.local/share/sni-qt/icons/TVGuiDelegate` seem to be ok (the names there are the same as in `/tmp/sni-qt_TVGuiDelegate_2694-jFooF2/icons/hicolor/24x24/apps`.

Any ideas?

**Comment by bil-elmoussaoui** [comment]
I've no idea.. it's just happened or after an update?

**Comment by wa4557** [comment]
I don't know. Worked great all the time, reinstalled teamviewer (same version) and it stopped working

**Comment by bil-elmoussaoui** [comment]
Have you tried to reinstall the application again?

**Comment by wa4557** [comment]
sure

**Comment by bil-elmoussaoui** [comment]
If skype works, and teamviewer wroked before the only thing that i can think of is that somehow teamviewer does not use `libsniqt.so` anymore.. but it's the same version :( can you try a downgrade?

**Comment by bil-elmoussaoui** [comment]
@wa4557 You can still reproduce this ?

**Comment by wa4557** [comment]
Sadly yes :(

**Comment by bil-elmoussaoui** [comment]
@wa4557 Can you build the latest version of sni-qt and try again? If it's not working, what distro/ubuntu version you're using? the same for the desktop env so i can try it too.

**Comment by wa4557** [comment]
Tried to build it from source. Same behaviour. Skype works but teamviewer doesn't. Using Ubuntu 16.04

**Comment by bil-elmoussaoui** [comment]
I will try to install Ubuntu on a VM and check if i can reproduce this

**Comment by Floofies** [comment]
I am running Xubuntu 16.04, and I see the same issue.

**Comment by leoheck** [comment]
Same here! Ubuntu 16.04

**Comment by bil-elmoussaoui** [comment]
I will need some help here! Can you check on `/tmp/` if you will find any icon that Teamviewer uses for it's tray icon?

**Comment by leoheck** [comment]
Yeah, I found it. 

Main path:
```bash
/tmp/sni-qt_TVGuiDelegate_28669-MSDMwo/icons/hicolor/64x64/apps
```

Icon Sizes:
```bash
lheck@moon > ls /tmp/sni-qt_TVGuiDelegate_28669-MSDMwo/icons/hicolor
128x128  16x16  24x24  32x32  48x48  64x64
```

File names:
```bash
TVGuiDelegate_28669_0b040b0d9ec00ce0d8189ece93cd2b7f.png
TVGuiDelegate_28669_4327113cab136a09fac832e66878159a.png
TVGuiDelegate_28669_c28d37df9872311f7c6b295b70b8a39d.png
TVGuiDelegate_28669_efbb734158e93591c95134fbc4e9d667.png
```

**Comment by bil-elmoussaoui** [comment]
Could you paste a screenshot of the icons? The latest icon `TVGuiDelegate_28669_efbb734158e93591c95134fbc4e9d667.png`

**Comment by leoheck** [comment]
Sure, totally forgot that. 

![teamviwericons](https://cloud.githubusercontent.com/assets/1277920/19947953/82910f18-a131-11e6-8678-49a2336c0fb5.png)

**Comment by bil-elmoussaoui** [comment]
Well, there was a missing icon! but it's the teamviewer error tray icon! I'm going to install Ubuntu to investigate this

**Comment by wa4557** [comment]
Even with the new teamviewer 12 it doesn't work... Tried everything, no idea :(

**Comment by bil-elmoussaoui** [comment]
It most be the patched version of sni-qt then, we need to figure out how to get the latest version! as the PPA was not updated since few weeks or months now..

**Comment by bil-elmoussaoui** [comment]
@wa4557 Can you guys try with the new PPA, created by  @varlesh ?

**Comment by varlesh** [comment]
On my PPA package for 16.04 from PPA sni-qt-eplus. I'm build package for 16.10 only.
Also original sni-qt version semilar on Ubuntu 16.04, 16.10 and 17.04:
http://packages.ubuntu.com/search?keywords=sni-qt&searchon=names&suite=all&section=all

**Comment by bil-elmoussaoui** [comment]
with the latest version of sni-qt it's possible to debug this much more easier. Just update to the latest sni-qt, and run teamviewer once the gui is open click on the tray and then "open log files...". After that you can easily get the log of the gui, on the `gui` file.

**Comment by wa4557** [comment]
Ok interesting behaviour: teamviewer seems to use sni-qt (in the debug logs sni-qt messages are present), but obviously not the one we install, because if I add custom debug messages they do not show up in the log. 

I think it is just a matter of finding the right library

**Comment by bil-elmoussaoui** [comment]
Do you get those log message using megasync --debug?

**Comment by wa4557** [comment]
Yes

**Comment by wa4557** [comment]
Ok one step forward to steps back: Teamviewer is still using the same library (if I put debug messages very early in the program they show up), but the methods in `iconcache.cpp` are never called. Somewhere something has to go wrong

**Comment by bil-elmoussaoui** [comment]
@wa4557 Skype does not provide any possible way to do that, we just need to figure out where to log files are stored

**Comment by wa4557** [comment]
If we figure out why teamviewer is not working I guess skype will start to work as well

**Comment by wa4557** [comment]
I just figured out how to make teamviewer work again...

If you add this icon `TVGuiDelegate_3524_cbdf5ff3eb7755ddd146a5b81f94b925-panel` to `/usr/share/Numix/` the correct icon is shown (this works also with all other icons). 

So teamviewer is using a themed icon, with a very weird name

**Comment by bil-elmoussaoui** [comment]
@wa4557 so what should we do about this? :(

**Comment by bil-elmoussaoui** [comment]
@wa4557 Can you try with something else ? like Megasync or any other Qt application ?

**Comment by bil-elmoussaoui** [comment]
Btw, i guess this is somehow related https://github.com/bil-elmoussaoui/sni-qt/blob/565f89281197a867c23bc8871e1389b502a3e5ef/src/iconcache.cpp#L90

**Comment by wa4557** [comment]
It only works with teamviewer. The other icons are picked from `/tmp` megasync. You should try skype (which is using icons from `tmp` for me)

**Comment by wa4557** [comment]
It is even worse because, the number 3524 changes everytime you open teamviewer `TVGuiDelegate_3524_cbdf5ff3eb7755ddd146a5b81f94b925-panel`

**Comment by wa4557** [comment]
Btw: with this command `dbus-send --type=method_call --print-reply --dest=com.canonical.indicator.application /com/canonical/indicator/application/service com.canonical.indicator.application.service.GetApplications` we can get the correct icon informations

**Comment by bil-elmoussaoui** [comment]
I will take a look for skype, it must be the same case as teamviewer. Btw what do you think about this #297 ?

**Comment by bil-elmoussaoui** [comment]
It shows up as you explained for TeamViewer :( btw, skype does not show the tray icon anymore here i don't know why...

**Comment by wa4557** [comment]
But that's not necessarily a bad thing. We just have to figure out where teamviewer get its icon, and change the name

**Comment by wa4557** [comment]
@bil-elmoussaoui I'm working again on fixing this, but the script doesn't work anymore for sni-qt apps!? running `hardcode-tray --only teamviewer` gives no icons in `.local/share/sni-qt...`

**Comment by bil-elmoussaoui** [comment]
It works without any issues in my case :/

**Comment by wa4557** [comment]
argh... Can you try remove all the folders in there and see if the folders are created? This doesn't happen for me

**Comment by bil-elmoussaoui** [comment]
Can confirm that! if i remove the folders, they're not created automatically and so the icons are not installed

**Comment by bil-elmoussaoui** [comment]
Fixed on master

**Comment by wa4557** [comment]
Thanks. There is also the issue, that some files have the wrong fileending (`.svg.svg`)

```
lrwxrwxrwx 1 root root 93 Mai 24 14:30 02d13a3a478e96b7e4fa7f7241221170.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/4cd9545d0021db224685d863ac738f91.svg
lrwxrwxrwx 1 root root 57 Mai 24 14:30 0b040b0d9ec00ce0d8189ece93cd2b7f.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator.svg
lrwxrwxrwx 1 root root 97 Mai 24 14:30 1ee7ede4f6037d6c4ebcdb4cf9fb8d44.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/54b99333baa6a26fda3eb8ce6d664bd5.svg.svg
lrwxrwxrwx 1 root root 93 Mai 24 14:30 2e1a63598adb1734de0590e3c70ea98d.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/0b040b0d9ec00ce0d8189ece93cd2b7f.svg
lrwxrwxrwx 1 root root 67 Mai 24 14:30 4327113cab136a09fac832e66878159a.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-connected.svg
lrwxrwxrwx 1 root root 62 Mai 24 14:30 4cd9545d0021db224685d863ac738f91.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-busy.svg
lrwxrwxrwx 1 root root 63 Mai 24 14:30 54b99333baa6a26fda3eb8ce6d664bd5.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-error.svg
lrwxrwxrwx 1 root root 93 Mai 24 14:30 650a76ace6dc9ab50d83961afbf5482f.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/c28d37df9872311f7c6b295b70b8a39d.svg
lrwxrwxrwx 1 root root 65 Mai 24 14:30 86e4f5bf63a6fa1725afd2e08e0ce105.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-offline.svg
lrwxrwxrwx 1 root root 97 Mai 24 14:30 a41d8570ea7ee153fb767dd577921097.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/0b040b0d9ec00ce0d8189ece93cd2b7f.svg.svg
lrwxrwxrwx 1 root root 62 Mai 24 14:30 c28d37df9872311f7c6b295b70b8a39d.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-away.svg
lrwxrwxrwx 1 root root 93 Mai 24 14:30 cbdf5ff3eb7755ddd146a5b81f94b925.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/4327113cab136a09fac832e66878159a.svg
lrwxrwxrwx 1 root root 93 Mai 24 14:30 efbb734158e93591c95134fbc4e9d667.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/54b99333baa6a26fda3eb8ce6d664bd5.svg
lrwxrwxrwx 1 root root 93 Mai 24 14:30 f8a91d87682c4c956f3d45416ef72737.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/86e4f5bf63a6fa1725afd2e08e0ce105.svg
```

**Comment by bil-elmoussaoui** [comment]
Hmmm, the issue is in symlinks_installer in the decorators file. I will see what i can do later, currently working on a way to fix nwjs apps

**Comment by bil-elmoussaoui** [comment]
Fixed the broken symlinks on master :)

**Comment by wa4557** [comment]
Well I was looking in the wrong direction all the time: Teamviewer is not using sni-qt anymore :/ Uninstall sni-qt and the icon is still showing. Now I need to figure out where this is happening

**Comment by wa4557** [comment]
You didn't fix the issue with the symlinks btw, now it is even worse and the svg extension is completely missing;)

```
lrwxrwxrwx 1 root root 89 Mai 24 17:50 02d13a3a478e96b7e4fa7f7241221170.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/4cd9545d0021db224685d863ac738f91
lrwxrwxrwx 1 root root 57 Mai 24 17:50 0b040b0d9ec00ce0d8189ece93cd2b7f.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator.svg
lrwxrwxrwx 1 root root 89 Mai 24 17:50 1ee7ede4f6037d6c4ebcdb4cf9fb8d44.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/54b99333baa6a26fda3eb8ce6d664bd5
lrwxrwxrwx 1 root root 89 Mai 24 17:50 2e1a63598adb1734de0590e3c70ea98d.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/0b040b0d9ec00ce0d8189ece93cd2b7f
lrwxrwxrwx 1 root root 67 Mai 24 17:50 4327113cab136a09fac832e66878159a.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-connected.svg
lrwxrwxrwx 1 root root 62 Mai 24 17:50 4cd9545d0021db224685d863ac738f91.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-busy.svg
lrwxrwxrwx 1 root root 63 Mai 24 17:50 54b99333baa6a26fda3eb8ce6d664bd5.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-error.svg
lrwxrwxrwx 1 root root 89 Mai 24 17:50 650a76ace6dc9ab50d83961afbf5482f.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/c28d37df9872311f7c6b295b70b8a39d
lrwxrwxrwx 1 root root 65 Mai 24 17:50 86e4f5bf63a6fa1725afd2e08e0ce105.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-offline.svg
lrwxrwxrwx 1 root root 89 Mai 24 17:50 a41d8570ea7ee153fb767dd577921097.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/0b040b0d9ec00ce0d8189ece93cd2b7f
lrwxrwxrwx 1 root root 62 Mai 24 17:50 c28d37df9872311f7c6b295b70b8a39d.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-away.svg
lrwxrwxrwx 1 root root 89 Mai 24 17:50 cbdf5ff3eb7755ddd146a5b81f94b925.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/4327113cab136a09fac832e66878159a
lrwxrwxrwx 1 root root 89 Mai 24 17:50 efbb734158e93591c95134fbc4e9d667.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/54b99333baa6a26fda3eb8ce6d664bd5
lrwxrwxrwx 1 root root 89 Mai 24 17:50 f8a91d87682c4c956f3d45416ef72737.svg -> /home/andreas/.local/share/sni-qt/icons/TVGuiDelegate/22/86e4f5bf63a6fa1725afd2e08e0ce105
```

and there is another missing print statement

```
Dropbox             [###.....................................] 5/79 6.3% 0.48s
Franz               [#####...................................] 9/79 11.4% 0.58s
Google Chrome       [########................................] 16/79 20.3% 5.98s
Google Music Manager[#########...............................] 17/79 21.5% 0.0s
Keepassx            [##########..............................] 19/79 24.1% 0.23s
Megasync            [############............................] 23/79 29.1% 0.0s
OwnCloud            [###############.........................] 29/79 36.7% 0.0s
Skype               [##############################..........] 59/79 74.7% 11.82s
Spotify             [##################################......] 68/79 86.1% 2.24s
Teamviewer          [#####################################...] 74/79 93.7% 0.0s
Telegram            [#######################################.] 77/79 97.5% 0.55s
Whatsie             [########################################] 79/79 100.0% 0.8s
```

**Comment by bil-elmoussaoui** [comment]
hmm? are you sure about that ? Because i don't have this issue myself :(
```bash
lrwxrwxrwx 1 root  root    91 24 mai 17:59 02d13a3a478e96b7e4fa7f7241221170.svg -> /home/bilal/.local/share/sni-qt/icons/TVGuiDelegate/22/4cd9545d0021db224685d863ac738f91.svg
lrwxrwxrwx 1 root  root    57 24 mai 17:59 0b040b0d9ec00ce0d8189ece93cd2b7f.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator.svg
lrwxrwxrwx 1 root  root    91 24 mai 17:59 1ee7ede4f6037d6c4ebcdb4cf9fb8d44.svg -> /home/bilal/.local/share/sni-qt/icons/TVGuiDelegate/22/54b99333baa6a26fda3eb8ce6d664bd5.svg
lrwxrwxrwx 1 root  root    91 24 mai 17:59 2e1a63598adb1734de0590e3c70ea98d.svg -> /home/bilal/.local/share/sni-qt/icons/TVGuiDelegate/22/0b040b0d9ec00ce0d8189ece93cd2b7f.svg
lrwxrwxrwx 1 root  root    67 24 mai 17:59 4327113cab136a09fac832e66878159a.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-connected.svg
lrwxrwxrwx 1 root  root    62 24 mai 17:59 4cd9545d0021db224685d863ac738f91.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-busy.svg
lrwxrwxrwx 1 root  root    63 24 mai 17:59 54b99333baa6a26fda3eb8ce6d664bd5.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-error.svg
lrwxrwxrwx 1 root  root    91 24 mai 17:59 650a76ace6dc9ab50d83961afbf5482f.svg -> /home/bilal/.local/share/sni-qt/icons/TVGuiDelegate/22/c28d37df9872311f7c6b295b70b8a39d.svg
lrwxrwxrwx 1 root  root    65 24 mai 17:59 86e4f5bf63a6fa1725afd2e08e0ce105.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-offline.svg
lrwxrwxrwx 1 root  root    91 24 mai 17:59 a41d8570ea7ee153fb767dd577921097.svg -> /home/bilal/.local/share/sni-qt/icons/TVGuiDelegate/22/0b040b0d9ec00ce0d8189ece93cd2b7f.svg
lrwxrwxrwx 1 root  root    62 24 mai 17:59 c28d37df9872311f7c6b295b70b8a39d.svg -> /usr/share/icons/Numix/22/status/teamviewer-indicator-away.svg
lrwxrwxrwx 1 root  root    91 24 mai 17:59 cbdf5ff3eb7755ddd146a5b81f94b925.svg -> /home/bilal/.local/share/sni-qt/icons/TVGuiDelegate/22/4327113cab136a09fac832e66878159a.svg
lrwxrwxrwx 1 root  root    91 24 mai 17:59 efbb734158e93591c95134fbc4e9d667.svg -> /home/bilal/.local/share/sni-qt/icons/TVGuiDelegate/22/54b99333baa6a26fda3eb8ce6d664bd5.svg
lrwxrwxrwx 1 root  root    91 24 mai 17:59 f8a91d87682c4c956f3d45416ef72737.svg -> /home/bilal/.local/share/sni-qt/icons/TVGuiDelegate/22/86e4f5bf63a6fa1725afd2e08e0ce105.svg
```

**Comment by wa4557** [comment]
Yeah sorry, you're right

**Comment by bil-elmoussaoui** [comment]
Well, maybe we can try to see if those icons are on the binary file? And provide a fix for the rest of the binary files and ditch sni-qt forever. If we ever have any issue with an application, we remove it support ;)

**Comment by bil-elmoussaoui** [comment]
I will boot with my Ubuntu VM and try to digg more

**Comment by wa4557** [comment]
Ok I found the icons in the binary file (.dll file) here: `/opt/teamviewer/tv_bin/wine/drive_c/TeamViewer/TeamViewer_Resource_{language}.dll`. Do you have any idea how to replace them? (They are ico files)

**Comment by bil-elmoussaoui** [comment]
@wa4557 I don't think that there's a signature for ico files like the png ones in order to get the right icons and not break the application

**Comment by wa4557** [comment]
Extracting is possible, I have a problem to put them back in

**Comment by bil-elmoussaoui** [comment]
I can't help you with that :( my main machine uses gnome & sni-qt doesn't work as expected #296

**Comment by wa4557** [comment]
You don't need sni-qt to show the icon though for teamviewer

**Comment by bil-elmoussaoui** [comment]
Alright, how did you extracted the icons?

**Comment by wa4557** [comment]
`wrestool -x -n 10811 TeamViewer_Resource_{yourlang}.dll > extracted.ico`

**Comment by bil-elmoussaoui** [comment]
But looking at some files  `/opt/teamviewer/tv_bin/scripts/tvw_main`
There's those lines of code 
```bash
  if isNative; then
    exec $TV_BIN_DIR/TeamViewer              $inst "$@" &> "$logPath"
  else
    exec wine 'c:\TeamViewer\TeamViewer.exe' $inst "$@" &> "$logPath"
  fi
```
i think that what happening in your case is teamviewer is no more used as a "native" app, so it uses wine to run it, and so sni-qt is no more working.

**Comment by wa4557** [comment]
on linux teamviewer is always run with wine. It is and always has been an windows exe file under the hood

**Comment by bil-elmoussaoui** [comment]
I've done some testing today using elementary OS. Frech install, and using the PPA to install sni-qt.
![screenshot from 2017-05-29 00 23 17](https://cloud.githubusercontent.com/assets/7660997/26532601/08228be0-4405-11e7-86bd-9a6bdcb9c025.png)
As you can see the tray icon is not showing any icon at all...By looking at the log files that can be found in `/var/log/teamviewer12` I've found those things
```bash
"sni-qt/26923" DEBUG 00:21:57.210 virtual QAbstractSystemTrayIconSys* StatusNotifierItemFactory::create(QSystemTrayIcon*) 
"sni-qt/26923" DEBUG 00:21:57.210 StatusNotifierItem::StatusNotifierItem(QSystemTrayIcon*, IconCache*) this: StatusNotifierItem(0xef63a7b0) 
"sni-qt/26923" DEBUG 00:21:57.210 StatusNotifierItem::StatusNotifierItem(QSystemTrayIcon*, IconCache*) m_serviceName: "org.kde.StatusNotifierItem-26923-1" 
"sni-qt/26923" DEBUG 00:21:57.210 StatusNotifierItem::StatusNotifierItem(QSystemTrayIcon*, IconCache*) m_objectPath: "/StatusNotifierItem" 
"sni-qt/26923" DEBUG 00:21:57.214 virtual void StatusNotifierItem::updateMenu() menu: QMenu(0xef61f468) 
"sni-qt/26923" DEBUG 00:21:57.214 void StatusNotifierItemFactory::registerItem(StatusNotifierItem*) 
"sni-qt/26923" DEBUG 00:21:57.215 virtual void StatusNotifierItem::updateVisibility() NewStatus( "Active" ) 
"sni-qt/26923" DEBUG 00:21:57.216 virtual void StatusNotifierItem::updateVisibility() NewStatus( "Passive" ) 
"sni-qt/26923" DEBUG 00:21:57.216 virtual void StatusNotifierItem::updateVisibility() NewStatus( "Active" ) 
fixme:nls:GetGeoInfoW -1 4 0x33fcbc 3 0
Could not save icon as '/tmp/sni-qt_TVGuiDelegate_26923-Oyhkta/icons/hicolor/24x24/apps/TVGuiDelegate_26923_a41d8570ea7ee153fb767dd577921097.png'
```

**Comment by wa4557** [comment]
Yes. I think I came closer to the solution (c++ is really hard for me though...)

When I change this function `connectToSnw`

to 

```
void StatusNotifierItemFactory::connectToSnw()
{   
    SNI_DEBUG;
    m_isAvailable = false;
    QDBusInterface snw(SNW_SERVICE, SNW_PATH, SNW_IFACE);
    if (!snw.isValid()) {
        SNI_WARNING << "Invalid interface to SNW_SERVICE";
        return;
    }

    QDBusConnection bus = QDBusConnection::sessionBus();
    bus.connect(SNW_SERVICE, SNW_PATH, SNW_IFACE, "StatusNotifierHostRegistered", "",
        this, SLOT(slotHostRegisteredWithSnw()));

    // FIXME: Make this async?
    QVariant value = snw.property("IsStatusNotifierHostRegistered");
    if (!value.canConvert<bool>()) {
        SNI_WARNING << "IsStatusNotifierHostRegistered returned something which is not a bool:" << value;
        return;
    }
    m_isAvailable = value.toBool();
    SNI_VAR(m_isAvailable);
    // THIS IS CALLED IN TEAMVIEWER
    qCritical("I don't know when I'm called");
    Q_FOREACH(StatusNotifierItem* item, m_items) {
        registerItem(item);
      
    }
}
```

I get this in the logfile:

```
"sni-qt/21087" DEBUG 10:10:16.115 StatusNotifierItemFactory::StatusNotifierItemFactory() m_iconCacheDir: "/tmp/sni-qt_TVGuiDelegate_21087-Hy1Ajq" 
"sni-qt/21087" DEBUG 10:10:16.118 void StatusNotifierItemFactory::connectToSnw() 
"sni-qt/21087" DEBUG 10:10:16.120 void StatusNotifierItemFactory::connectToSnw() m_isAvailable: true 
I don't know when I'm called
"sni-qt/21087" DEBUG 10:10:16.122 StatusNotifierItemFactory::StatusNotifierItemFactory() m_iconCacheDir: "/tmp/sni-qt_TVGuiDelegate_21087-g4gDXy" 
"sni-qt/21087" DEBUG 10:10:16.122 void StatusNotifierItemFactory::connectToSnw() 
"sni-qt/21087" DEBUG 10:10:16.122 void StatusNotifierItemFactory::connectToSnw() m_isAvailable: true 
err:secur32:SECUR32_initSchannelSP TLS library not found, SSL connections will fail
"sni-qt/21087" DEBUG 10:10:16.131 virtual QAbstractSystemTrayIconSys* StatusNotifierItemFactory::create(QSystemTrayIcon*) 
"sni-qt/21087" DEBUG 10:10:16.132 StatusNotifierItem::StatusNotifierItem(QSystemTrayIcon*, IconCache*) this: StatusNotifierItem(0xf3037d90) 
"sni-qt/21087" DEBUG 10:10:16.132 StatusNotifierItem::StatusNotifierItem(QSystemTrayIcon*, IconCache*) m_objectPath: "/org/kde/statusnotifieritem/1" 
"sni-qt/21087" DEBUG 10:10:16.132 virtual void StatusNotifierItem::updateMenu() menu: QMenu(0xf3b865d8) 
"sni-qt/21087" DEBUG 10:10:16.132 void StatusNotifierItemFactory::registerItem(StatusNotifierItem*) 
```

This means that the program tries to create the correct icon (This is why my qCritical shows up one time in the logfile). But it somehow fails and calls a different `sni-qt` version somewhere. I am yet to find out where this happens...

**Comment by bil-elmoussaoui** [comment]
I guess that teamviewer ships with an other version of sni-qt? and falls back to it if the system one is broken

**Comment by wa4557** [comment]
maybe it's wine itself

**Comment by bil-elmoussaoui** [comment]
:( I will take another look after the finals. The only issue we still have with a fully working Hardcode-Tray (for almost use cases) is sni-qt...doesn't work at all on Gnome & with this teamviewer issue. But we will figure it out!

**Comment by artemlyubin** [comment]
Any progress with this?

**Comment by wa4557** [comment]
Unfortunately it seems to be impossible for now :( Let's see what the future brings...
