### ISSUE TITLE
PPA for Ubuntu 14.04 / 16.04 / 16.10

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#198]
I'm create PPA for Xenial and Trusty with patched sni-qt and hardcode-tray. Please update README.

**INSTALL (Ubuntu 14.04 / 16.04 / 16.10):**
```
sudo add-apt-repository ppa:varlesh-l/hardcode-tray
sudo apt update
sudo apt install --reinstall sni-qt hardcode-tray
```
**PPA link**:
https://launchpad.net/~varlesh-l/+archive/ubuntu/hardcode-tray/+packages

**DEPENDS**:
- git
- python3
- wget
- inkscape
- python3-cairosvg
- gir1.2-rsvg-2.0
- libqt4-svg
- sni-qt (=0.2.8-0~81~ubuntu14.04.1) and sni-qt (=0.2.8-0~81~ubuntu16.04.1)

Option `hardcode-tray -ug` worked correctly

**Comment by bil-elmoussaoui** [comment]
Can you run the building for other versions of ubuntu too?

**Comment by varlesh** [comment]
No. I'm only copy sni-qt packages from repository **ppa:cybre/sni-qt-eplus** (availiable packages for 14.04 -16.04 only. ) and build hardcode-tray for 14.04 and 16.04. 
Ubuntu 14.10, 15.04, 15.10 - discontinued!

**Comment by varlesh** [comment]
For Ubuntu 16.10 i don't know how patch sni-qt and can't test (i'm use only LTS-releses). Also it's really not needed, because 16.10 supported only 9 months

**Comment by varlesh** [comment]
@bil-elmoussaoui Try build for Yakkety:
https://launchpadlibrarian.net/292653209/buildlog_ubuntu-yakkety-amd64.sni-qt_0.2.8-0~81~ubuntu16.10_BUILDING.txt.gz
If it's ok, im build hardcode-tray for Ubuntu 16.10. But, i'm not test this!!!

**Comment by varlesh** [comment]
Added 16.10

**Comment by bil-elmoussaoui** [comment]
@varlesh Thank you!! 
@Foggalong Can you try this PPA for sni-qt?

**Comment by bil-elmoussaoui** [comment]
@varlesh Can you open a PR with the modification ?

**Comment by varlesh** [comment]
ok

**Comment by varlesh** [comment]
Done, but need fix depends list. I don't know how

**Comment by bil-elmoussaoui** [comment]
Fixed! thank you!!

**Comment by Foggalong** [comment]
@bil-elmoussaoui While the script installs and runs fine from the PPA, this still isn't fixing ownCloud for me on 16.10 :/

**Comment by bil-elmoussaoui** [comment]
@Foggalong It must be sni-qt :( can you tell me which system are you using so i can try to recreate the same system as a VM and see if i can figure it out

**Comment by Foggalong** [comment]
@bil-elmoussaoui Ubuntu 16.10, XFCE Panel, ownCloud 2.2.2, sni-qt & hardcode tray from the PPA mentioned here.
