### ISSUE TITLE
Archlinux --theme 

### ISSUE THREAD

**Issue by kadza93** [bil-elmoussaoui/Hardcode-Tray#221]
I have installed hardcode-tray using yaourt, when I use `hardcode-tray` in terminal I get Adwaita icons detected even tho I don't use them. So i did try to force theme via `hardcode-tray --theme Numix` and after trying to apply to all i get following error.

```
hardcode-tray --theme Numix                                         12:28  20.11.16  0.17G RAM 

(script.py:11558): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(script.py:11558): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(script.py:11558): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Numix
Svg to png functions are : Disabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 1
Applying now..

fixing failed with error:####################################] 1/1 100.0%
	Traceback (most recent call last):
	  File "/opt/Hardcode-Tray/database/scripts/chrome", line 27, in <module>
	    data_pack.WriteDataPack(dataPack.resources, filename, 0)
	  File "/opt/Hardcode-Tray/database/scripts/data_pack.py", line 105, in WriteDataPack
	    content = WriteDataPackToString(resources, encoding)
	  File "/opt/Hardcode-Tray/database/scripts/data_pack.py", line 93, in WriteDataPackToString
	    data_offset += len(resources[id])
	TypeError: object of type 'NoneType' has no len()
	

Done , Thank you for using the Hardcode-Tray fixer!
```

I really have no clue whats wrong i'm on kde de.

Edit: Here is the screen shoot if it makes it more readable.

![screenshot_20161120_124011](https://cloud.githubusercontent.com/assets/9012882/20462846/ad2dbfbe-af1e-11e6-880a-d1cd843ecb7e.png)

**Comment by bil-elmoussaoui** [comment]
Those errors 
```bash
(script.py:11558): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(script.py:11558): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(script.py:11558): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
```
Are due to your Gtk theme.
Can you try to upgrade to the git version using `hardcode-tray --update-git` and try again?
I think the issue is due to a missing file in your chrome/chromium installation (the file resources.pak must be broken :( )

**Comment by kadza93** [comment]
Nope still the same. Mind you i'm using theme from [this](https://github.com/varlesh/Arc-Dark-KDE) repo.

**Comment by bil-elmoussaoui** [comment]
Can you try reinstalling Chrome/chromium ?

**Comment by kadza93** [comment]
Maybe because i'm on beta of chrome, i'l try installing stable release.

**Comment by bil-elmoussaoui** [comment]
Both versions are supported. Just give the reinstallation a try

**Comment by kadza93** [comment]
Reinstalled both, same error.

**Comment by kadza93** [comment]
When i try `hardcode-tray --theme Numix --only franz` i get `No apps to fix! Please report on GitHub if this is not the case` i don't need really to fix chrome because i will not be displaying it but nevertheless its not working for some reason.

**Comment by bil-elmoussaoui** [comment]
How did you installed franz? Using yaourt? I will see how to fix the chrome issue

**Comment by kadza93** [comment]
Yeah i installed both chrome and franz via `yaourt`.

**Comment by bil-elmoussaoui** [comment]
Which folders do you have on `/opt/`? (try something like `ls`)

**Comment by bil-elmoussaoui** [comment]
Ping?

**Comment by bil-elmoussaoui** [comment]
I pushed a fix to avoid the issue you're having with the chrome icons. For franz, you must have installed `franz-bin`, I pushed a new fix for this one too.

**Comment by kadza93** [comment]
@bil-elmoussaoui Sorry for late answer i have been busy. So update managed to try and change the theme but still no luck.
![screenshot_20161122_022338](https://cloud.githubusercontent.com/assets/9012882/20507440/f8c637c0-b05a-11e6-851d-46166af7f360.png)

I did try with numix same result.

**Comment by kadza93** [comment]
As for /opt
![ls-l](https://cloud.githubusercontent.com/assets/9012882/20507560/a50f1e8e-b05b-11e6-950b-38f730623b8f.png)

**Comment by bil-elmoussaoui** [comment]
Please install Inkscape. As you can see svg to png lcons are not active on your screenshot. See README for more information
