### ISSUE TITLE
sni-qt improvements

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#243]
In order to get all the sni-qt issues fixed and help us improve user experience here's a list of things that i will try to sort out if have some free time soon.

- [x] In order to debug issues correctly. We must add a log file somewhere and save all important information; icon names, application name and stuff like that. We can save that here `~/.cache/sni-qt/logs`
- [x] The possibility to use SVG icons too instead of using only png icons which are really ugly.

**Comment by wa4557** [comment]
Svg is easy; I already know how to do that. We have to change the way sni-qt icons are handled than though, since we have to do everything with symlinks then.

Currently I'm trying to figure out what's wrong with teamviewer, maybe this solves also the owncloud issue (which I cannot reproduce)

**Comment by wa4557** [comment]
It should now be possible to use svg icons instead of png icons. @bil-elmoussaoui Can you try out as well?

**Comment by bil-elmoussaoui** [comment]
I have to build sni-qt for Archlinux first, i will report back this evening

**Comment by bil-elmoussaoui** [comment]
By the way do you have any idea what's this is file for? /etc/xdg/sni-qt.conf?

**Comment by wa4557** [comment]
No idea. 

We have to change the way the script works slightly, in order to make it work with svg files. We can do everything symlink (doesn't matter if they are svg or png), but we have to store them in `.local/share/sni-qt/icons/{app}/{size}/`. 

The modified sni-qt package, then looks for these folders and can determine the correct sizes. The problem is, that there is no easy way to determine original svg sizes in Qt

**Comment by wa4557** [comment]
Yeah with my latest improvements (coding in c++ is really really hard for me). We can now use svg icons as well. But we have to change the script as I said already earlier.

**Comment by bil-elmoussaoui** [comment]
Can you update the python script too? If you can't I will do that ;) and my C++ is not that bad, I think I will be able to implement a correct logging system

**Comment by wa4557** [comment]
I can. But I'll do that on a separate branch for now until everything is set up correctly.

**Comment by bil-elmoussaoui** [comment]
Perfect. What do you think about moving our sni-qt branch from bzr
(launchpad) to github? This will attract more attention ;)

Le 10 déc. 2016 10:00 PM, "Andreas Angerer" <notifications@github.com> a
écrit :

**Comment by wa4557** [comment]
I guess that's fine. I don't like bzr anyways, this way we can use git, and just mirror it to github for making the ppa

**Comment by wa4557** [comment]
Pushed changes to cript to new branch sni-qt

**Comment by bil-elmoussaoui** [comment]
Looks OK for me, but you have removed the chrome script :P

**Comment by wa4557** [comment]
added it again :)

**Comment by bil-elmoussaoui** [comment]
Done https://github.com/bil-elmoussaoui/sni-qt, i created a PPA just for sni-qt as we can't keep both of them on the same repo (as a branch for example...); Once the script grows bigger, we might move from a simple project repository to a much complex one. 

Added you also as a collaborator. I couldn't keep the bzr log history of commits and move it to git as bzr fastimport does not support feature commit-properties. And there's some useful information on the README file of the repository by the way.

I will work on creating a proper Arch package, and see if it's possible to do the same for Fedora. Once it's done,  we merge the sni-qt branch

**Comment by wa4557** [comment]
I think it would be a good idea to add this to the Same ppa. We can use git Import on launchpaf

**Comment by wa4557** [comment]
I uploaded the new git based sni-qt to the ppa. It seems to work. TeamViewer still doesnt though

**Comment by bil-elmoussaoui** [comment]
Just tried the new PPA on xubuntu. I think that the Installation of Hardcode-Tray is not working as it's supposed to. The hardcode-tray file should be installed on `/usr/bin` instead of `/opt/Hardcode-Tray/`

**Comment by wa4557** [comment]
But it Generates a symlink, doesnt it?

**Comment by bil-elmoussaoui** [comment]
Nop it doesn't as far as i can see. I tried `hardcode-tray` but i get the following message `hardcode-tray: command not found`

**Comment by bil-elmoussaoui** [comment]
also, we must bump the version number of sni-qt on our PPA as Ubuntu provide a non patched version of sni-qt with the version 0.2.8.0. Maybe using 0.2.8.1 for the beta tests and after that we release a 0.2.9.0; what do you think?
Also, we can enable debugging by default; in order to avoid users modifying files with root permissions

**Comment by wa4557** [comment]
Hmm. It does for me. I included a postinst routine that generates the symlink

**Comment by wa4557** [comment]
the latest version ubuntu provides is 2.7.0 so ours should be newer, actually

**Comment by bil-elmoussaoui** [comment]
On Ubuntu 16.04 i have 0.2.8 :P

**Comment by wa4557** [comment]
because you were installing from the previous ppa :P

**Comment by wa4557** [comment]
BTW: I'm not sure it is a good idea, that we changed the README just yet, because for now the script is not compatible with the ppa

**Comment by bil-elmoussaoui** [comment]
Alright! For the PPA, i will revert that ;) Btw, the svg icons or the patch doesn't seem to work as it should here on XFCE 
![screenshot_2016-12-11_15-36-17](https://cloud.githubusercontent.com/assets/7660997/21080768/92fc02fa-bfb7-11e6-9768-62ac1d7e73e4.png)
On this screenshot, the missing icon is used instead of Skype icons;

**Comment by wa4557** [comment]
Hmm. Do the icons exist in `/tmp`?

**Comment by bil-elmoussaoui** [comment]
No icons on /tmp. Only an empty folder, which is normal? the sni-qt:i386 is installed and i do have those icons
![screenshot_2016-12-11_15-52-53](https://cloud.githubusercontent.com/assets/7660997/21080843/e49e6c18-bfb9-11e6-8e63-c6af58adc868.png)

**Comment by wa4557** [comment]
Hmm the tmp folder shouldn't be empty. Maybe it's the 24px size that makes problems. 22px do work for me without problems

**Comment by wa4557** [comment]
can you try removing the whole local/share/sni-qt folder and the sni-qt folder in tmp and try again?

**Comment by bil-elmoussaoui** [comment]
It must be 22 for me too :o i think something is wrong on the sni-qt branch

**Comment by wa4557** [comment]
But xfce is 24, right?

https://github.com/bil-elmoussaoui/sni-qt/blob/master/src/iconcache.cpp#L140

Can you spot anything weird?

**Comment by wa4557** [comment]
For me it works also with 24px icons, you sure you're not doing anything wrong?

**Comment by bil-elmoussaoui** [comment]
I have removed XFCE the same day as i fucked up everything on my system.. I will reinstall it later and see if i can reproduce the same issue

**Comment by bil-elmoussaoui** [comment]
Okey, i have tried the latest PPA of sni-qt, on elementary OS 0.4. I have installed both skype and megasync; Megasync works fine, but skype does not :( 
![screenshot from 2016-12-15 02 27 20](https://cloud.githubusercontent.com/assets/7660997/21208630/76accc00-c26f-11e6-9d6f-eefc5d5aa522.png)

**Comment by KottV** [comment]
what megasync version you have? version <2.9.9 was Qt4-based, thus worked fine
my latest 2.9.10 uses Qt5, so, icon cannot be overrided (i guess)?

**Comment by wa4557** [comment]
what icons to you have in `.local/share/sni-qt/icons`? and in `/tmp`

**Comment by KottV** [comment]
I got some troubles right now: https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/250
so, there no any icons in .local/share/sni-qt/icons

AFAIK, Qt5-apps works with notification protocol native, without sni-qt (which for Qt4, obviously)

**Comment by bil-elmoussaoui** [comment]
@KottV I'm using MegaSync 2.9.10-25
@wa4557 Sorry for the delay, I had svg icons under 24 or 22 folder. I tried to use png icons but nothing changed :( is there a way to log each icon path? so we can see if the icons paths are correct or not. And we have also to enable logging by default and get the log file (we might need to add those information later to the wiki)

**Comment by KottV** [comment]
Excuse me for offtop, is your megasync built against Qt5?

**Comment by bil-elmoussaoui** [comment]
The default deb package is built using qt4 but on archlinux the package is built using qt5. And I really don't have any idea how to get that fixed as the icons are saved on tmp..

**Comment by wa4557** [comment]
Ok so the Icons are in the tmp folders?

**Comment by bil-elmoussaoui** [comment]
@wa4557 on XFCE the icons are shown in tmp folder. But on on Archlinux, i couldn't find the icons anywhere :( and  i don't know if we can modify the binary file (just by looking at the result of hexdump and xxd)

**Comment by wa4557** [comment]
Wait what are We talking about? Which binary File? So it works in xfce but Not on Arch? Are you using the correct code for Arch?

**Comment by bil-elmoussaoui** [comment]
I was talking about megasync icons. On elementary, skype icons are not on tmp folder and i was using the correct script and the  correct version of sni-qt.

**Comment by wa4557** [comment]
Fine. But this issue ist about sni-qt . I still sonst understand if my Code is now working or Not.

**Comment by wa4557** [comment]
Sni qt only works for qt4. It will NEVER work for qt5

**Comment by bil-elmoussaoui** [comment]
I think skype is like using an old version of Qt, which causes those issues. I will try with other qt applications that uses sni-qt and will see what i got ;)

**Comment by bil-elmoussaoui** [comment]
@wa4557 Just tried the following application 
- Flareget : works fine
- Bitcoin does not work even if the icon in /tmp is the correct icon (and it keep using the non monochrome icon) i will restart my system and try again
- Megasync works fine
- OwnCloud does not work as per #226 
- Skype neither
- Mumble works fine
- Museeq works fine too

**Comment by bil-elmoussaoui** [comment]
![screenshot from 2017-01-02 23 30 49](https://cloud.githubusercontent.com/assets/7660997/21596995/8727fedc-d143-11e6-84f6-2002a1e98643.png)

**Comment by wa4557** [comment]
owncloud switched to qt5 so it cannot work with sni-qt. skype is strange, since it works for me fine...
Bitcoin seems to be either qt4 or qt5 I don't know which version you are using.

**Comment by bil-elmoussaoui** [comment]
@wa4557 bitcoin in my case is using sni-qt (so it uses qt4) but the right icon is not shown...well, i think the best idea to test all of this is to release a beta version using sni-qt;  but first we need to test how the debugging works

**Comment by bil-elmoussaoui** [comment]
@wa4557 I'm going to merge your fix for sni-qt icons to master and release a new version. And we fix the issues that the users will report ;)

**Comment by bil-elmoussaoui** [comment]
On master! i'm going to create an AUR package for the pached version of sni-qt

**Comment by wa4557** [comment]
That's cool! Do you know where the logs are stored?

**Comment by bil-elmoussaoui** [comment]
Just run the application using terminal and you will have something like this 
```
"sni-qt/31386" DEBUG 23:01:13.831 StatusNotifierItemFactory::StatusNotifierItemFactory() m_iconCacheDir: "/tmp/sni-qt_flareget_31386-VaEb1c" 
"sni-qt/31386" DEBUG 23:01:13.831 void StatusNotifierItemFactory::connectToSnw() 
"sni-qt/31386" DEBUG 23:01:13.832 void StatusNotifierItemFactory::connectToSnw() m_isAvailable: true 
"sni-qt/31386" DEBUG 23:01:13.833 virtual QAbstractSystemTrayIconSys* StatusNotifierItemFactory::create(QSystemTrayIcon*) 
"sni-qt/31386" DEBUG 23:01:13.833 StatusNotifierItem::StatusNotifierItem(QSystemTrayIcon*, IconCache*) this: StatusNotifierItem(0x1aaa9b0) 
"sni-qt/31386" DEBUG 23:01:13.834 StatusNotifierItem::StatusNotifierItem(QSystemTrayIcon*, IconCache*) m_serviceName: "org.kde.StatusNotifierItem-31386-1" 
"sni-qt/31386" DEBUG 23:01:13.834 StatusNotifierItem::StatusNotifierItem(QSystemTrayIcon*, IconCache*) m_objectPath: "/StatusNotifierItem" 
"sni-qt/31386" DEBUG 23:01:13.834 virtual void StatusNotifierItem::updateMenu() menu: QMenu(0x1a79b00) 
"sni-qt/31386" DEBUG 23:01:13.840 void StatusNotifierItemFactory::registerItem(StatusNotifierItem*) 
"sni-qt/31386" DEBUG 23:01:13.841 virtual void StatusNotifierItem::updateVisibility() NewStatus( "Active" ) 
"sni-qt/31386" DEBUG 23:01:14.015 virtual void StatusNotifierItem::showMessage(const QString&, const QString&, QSystemTrayIcon::MessageIcon, int) "FlareGet Trial" "You 
```
We just need to add more debug information like the icon name used by the application

**Comment by bil-elmoussaoui** [comment]
@wa4557 btw bitcoin is working perfectly now! except TeamViewer and Skype, everything works as expected except the qt5 apps

**Comment by wa4557** [comment]
Weird. Just downloaded megasync and run it using the script. I don't see anything at the terminal..

**Comment by bil-elmoussaoui** [comment]
You should use --debug
