### ISSUE TITLE
DEB-packge broken symlink on /usr/bin

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#249]
On new PPA for hardcode-tray need install symlink on/usr/bin/hardcode-tray --> /opt/Hardcode-Tray/hardcode-tray
@wa4557

**Comment by varlesh** [comment]
because terminal not seen hardcode-tray on system:
```
alex@dell:~$ hardcode-tray
hardcode-tray: comand not found
alex@dell:~$ apt-cache show hardcode-tray
Package: hardcode-tray
Priority: optional
Section: misc
Installed-Size: 222
Maintainer: Alexey Varfolomeev <varlesh@gmail.com>
Architecture: all
Version: 3.5.2.1~596~ubuntu16.04.1
Depends: git, python3, python3-gi, wget, inkscape, python3-cairosvg, gir1.2-rsvg-2.0, libqt4-svg, sni-qt
Filename: pool/main/h/hardcode-tray/hardcode-tray_3.5.2.1~596~ubuntu16.04.1_all.deb
Size: 66036
MD5sum: 3c13d5a3d0b2d6f60b4d8671d2a29a65
SHA1: 338968034b0a269ca89edc05137453577d79d676
SHA256: e18d526e0f1d32d1ffe1961c5423e0965fd82f3eafa1d96e84eec11e43f87316
Description-en: Fixes Hardcoded tray icons in Linux
Description-md5: ef4f71b7163c1d07088bb639f29e3b1b

alex@dell:~$ 

```

**Comment by wa4557** [comment]
I'll have a look into that

**Comment by varlesh** [comment]
@wa4557 create symlink
```
ln -s hardcode-tray /opt/Hardcode-Tray/hardcode-tray
```
and add to debian/install:
```
Hardcode-Tray /opt/
hardcode-tray /usr/bin/
```

**Comment by wa4557** [comment]
I have a preinst script that should take care of that.

**Comment by varlesh** [comment]
and postrm too

**Comment by varlesh** [comment]
@wa4557 release 3.5.2.1~597~ubuntu16.04.1 not solve problem. File /usr/bin/hardcode-tray not exist

**Comment by varlesh** [comment]
@wa4557 Better variant create file on debina folder - i doing this for my PPA, because post-scripts not worked

**Comment by varlesh** [comment]
```
cd hardcode-tray-packaging/debian
ln -sf /opt/Hardcode-Tray/hardcode-tray /usr/bin/hardcode-tray
echo "debian/hardcode-tray /usr/bin/" >> install
```

**Comment by wa4557** [comment]
should be fixed

**Comment by bil-elmoussaoui** [comment]
Just tried the latest PPA, it works fine!

**Comment by varlesh** [comment]
NOT FIXED!
@wa4557 Why don't want create symlink on debian folder?
![image](https://cloud.githubusercontent.com/assets/8083855/21220068/aeb0bd76-c2d0-11e6-9ff9-8888de1fd909.png)

**Comment by wa4557** [comment]
But I do? In the install file, it should copy `hardcode-tray` to `/usr/bin` and `hardcode-tray` is a symlink

**Comment by varlesh** [comment]
i don't know why not working... Yes on package exist /usr/bin/hardcode-tray.
i extract hardcode-tray package (601 release). But not worked.

**Comment by wa4557** [comment]
But then the symlink should be invalid, not nonexisting. Argh its not working for me neither

**Comment by varlesh** [comment]
It's very strange
![image](https://cloud.githubusercontent.com/assets/8083855/21220459/57c6a910-c2d2-11e6-87f8-e5e778a35264.png)

**Comment by wa4557** [comment]
Strange. I'll investigate...

**Comment by varlesh** [comment]
> But then the symlink should be invalid, not nonexisting. Argh its not working for me neither
Create symlink on your PC:
`sudo ln -sf /opt/Hardcode-Tray/hardcode-tray /usr/bin/hardcode-tray`
copy file to debian folder from /usr/bin/hardcode-tray
and add to install:
`echo "debian/hardcode-tray /usr/bin/" >> install`

**Comment by wa4557** [comment]
https://stackoverflow.com/questions/9965717/debian-rules-file-make-a-symlink That seems to be the right way to do it

**Comment by varlesh** [comment]
Maybe, but if i'm create my ppa postinst and preinst scripts not worked... and i don't why

**Comment by varlesh** [comment]
I don't understand why on synaptic /usr/bin/hardcode-tray exist, but on system not? I'm confused :confused:

**Comment by varlesh** [comment]
really, it's strange...
![image](https://cloud.githubusercontent.com/assets/8083855/21220844/4993d06e-c2d4-11e6-8fdd-ed72ecfaeaa8.png)
Maybe it's bug apt?

**Comment by varlesh** [comment]
@wa4557 I know why it's happened ))
i'm delete package form system, but not delete folder /opt/Hardcode-Tray
if run once hardcode-tray (earlier)  - create files on /opt/Hardcode-Tray/database/scripts
after remove package apt can't delete /opt/Hardcode-Tray, because  have files /opt/Hardcode-Tray/database/scripts.
If reinstall package again - package not right installed.

**Comment by varlesh** [comment]
postrm script not worked too:
http://bazaar.launchpad.net/~andreas-angerer89/+junk/hardcode-tray-packaging/view/head:/debian/postrm
/opt/Hardcode-tray not deleted after remove package

**Comment by varlesh** [comment]
steps for reproduce:
- add PPA
- update package database
- run hardcode-tray and fix some icons
- delete package hardcode-tray
- install again package hardcode-tray

**Comment by varlesh** [comment]
@wa4557 it's hapenned once, i'm now reproduce steps and all installed fine...
closed
if anyone have this problem - need delete  /opt/Hardcode-Tray directory
