### ISSUE TITLE
Script shouldn't run as root user 

### ISSUE THREAD

**Issue by Armanmd** [bil-elmoussaoui/Hardcode-Tray#385]
### Specifications
- Hardcode-Tray version : ``
- Distribution : `kali rolling`
Linux Kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-1kali1 (2017-06-06) x86_64 GNU/Linux
- Gtk version : `+3`
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  ``
- Application version : ``

issue:

i install it with this commend:

cd /tmp && wget -O - https://raw.githubusercontent.com/bil-elmoussaoui/Hardcode-Tray/master/data/install.sh | bash
 in kali rolling (i loged as root user)

when i want to run Hardcode-Tray output is:
#:hardcode-tray
Script shouldn't be run as root

what to do ?

**Comment by bil-elmoussaoui** [comment]
You shouldn't run the script as a root user. Anyway this can be improved a bit, i will take a look as soon as i can

**Comment by Armanmd** [comment]
So I wait for your action :+1:

**Comment by bil-elmoussaoui** [comment]
Fixed on master ;) You might need to use `--theme` & `--size` as running the script as root user will not make it easier for the script to detect your default DE and so you correct icon size to use.
The script should be run using `sudo -E` to preserve the environment information

**Comment by Armanmd** [comment]
sudo -E hardcode-tray
Script shouldn't be run as root

**Comment by Armanmd** [comment]
i install script again but still not working

installtion commend:

cd /tmp && wget -O - https://raw.githubusercontent.com/bil-elmoussaoui/Hardcode-Tray/master/data/install.sh | bash

**Comment by AndydeCleyre** [comment]
@bil-elmoussaoui 

I wholeheartedly agree with you when you say

> You shouldn't run the script as a root user.

But it seems that presently the script will *only* run as root!

**Comment by bil-elmoussaoui** [comment]
Because the script already runs as root. if you run the script with double sudo it break some python code which could cause some permissions issues

**Comment by AndydeCleyre** [comment]
I'm not sure if I'm being clear. The behavior changed, breaking commands that worked a few revisions ago. 

Now, when you run the command as a regular user, the script exits without acting, instead insisting that the user run the command as root. 

I don't think this is intentional, is it?

**Comment by bil-elmoussaoui** [comment]
@AndydeCleyre It's intentional. I had a bash script that runs "sudo -E /op/hardcode-tray/hardcode-tray.py` but as i've moved to a build system (Meson here) in order to implement i18n; I had to remove the bash script that updates the script manually (latest stable version or git version) the bash script wasn't doing anything else anymore. So i ditched the bash script and i kept only Python code. Now you need to use sudo hardcode-tray` in order to get things to work. If you have a better idea, just let me know ;)

**Comment by AndydeCleyre** [comment]
Ok, thanks. Ideally, extra privileges would apply to only the few commands that really need it.

[Oomox](https://github.com/actionless/oomox/blob/master/oomoxify.sh#L269) for example builds themes in a temporary folder as the user, and only runs a privileged command at the end, to copy the files into place.

**Comment by bil-elmoussaoui** [comment]
Totally agree with you. i will work on improving this for the next release
