### ISSUE TITLE
Does not work with Google Chrome dev channel

### ISSUE THREAD

**Issue by viggy96** [bil-elmoussaoui/Hardcode-Tray#411]
### Specifications
- Hardcode-Tray version : `3.9`
- Distribution : `Ubuntu 16.04.2 LTS`
- Inkscape version : `0.91 r13725` 
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1` if installed
- Application name :  `Google Chrome dev channel`
- Application version : `61.0.3163.13 (Official Build) dev (64-bit)`

### Expected behavior and actual behavior
Change tray icon to appropriate theme icon

**Comment by bil-elmoussaoui** [comment]
The icon name must have been updated. Let me upgrade my Google Chrome Unstable and fix it :+1:

**Comment by bil-elmoussaoui** [comment]
Fixed on master

**Comment by viggy96** [comment]
Still does not appear to work. 
`Version 62.0.3192.0 (Official Build) dev (64-bit)`

**Comment by bil-elmoussaoui** [comment]
The icon name must have changed again :/ I'm going to give it a try :)

**Comment by bil-elmoussaoui** [comment]
It seems that our DataPak module is not valid anymore for the latest version of Pak :( this will need more investigation and maybe a rework of the Pak module.
This won't happen anytime soon; maybe in a month or so as i'm pretty busy at the moment

**Comment by Foggalong** [comment]
@bil-elmoussaoui will this also affect Chrome stable?

**Comment by bil-elmoussaoui** [comment]
it does only affect the dev version, but once the 61 is released it will be affected too. I will try to fix it before the end of the month

**Comment by GUiHKX** [comment]
61 went stable 19 days ago: https://chromereleases.googleblog.com/2017/09/stable-channel-update-for-desktop.html

**Comment by bil-elmoussaoui** [comment]
Ops i wasn't aware of that :) i will mark this as a high priority then ;)

**Comment by viggy96** [comment]
Current version is: `Version 63.0.3218.0 (Official Build) dev (64-bit)`

**Comment by bil-elmoussaoui** [comment]
Sorry guys for the long delay, i have been so busy those last days. I will work on this tomorrow and release a new version

**Comment by bil-elmoussaoui** [comment]
Should be fixed https://github.com/bil-elmoussaoui/Hardcode-Tray/commit/950a925e5a49e2a6d7282b9a4eda8fbe76f222d7

**Comment by viggy96** [comment]
Hardcode Tray appears to cause seg fault.

`[1:1:1022/174841.499009:ERROR:data_pack.cc(278)] Data pack file corruption: Alias #0 past end.
[1:1:1022/174841.499051:ERROR:resource_bundle.cc(810)] Failed to load /opt/google/chrome-unstable/resources.pak
Some features may not be available.
[9754:9754:1022/174841.664930:ERROR:data_pack.cc(278)] Data pack file corruption: Alias #0 past end.
[9754:9754:1022/174841.664979:ERROR:resource_bundle.cc(810)] Failed to load /opt/google/chrome-unstable/resources.pak
Some features may not be available.
--2017-10-22 17:48:41--  https://clients2.google.com/cr/report
Resolving clients2.google.com (clients2.google.com)... 74.125.196.101, 74.125.196.113, 74.125.196.139, ...
Connecting to clients2.google.com (clients2.google.com)|74.125.196.101|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/fd/4’

Crash dump id: a21a2fccba1ed231

     0K                                                        2.24M=0s

Segmentation fault
`

Reinstalling Chrome fixes this, but also reverts icon.

**Comment by bil-elmoussaoui** [comment]
I must have missed something, i will take a look right now

**Comment by bil-elmoussaoui** [comment]
I have been trying to figure out what doesn't work correctly and it seems that Chromium has some tests to verify the content of the pak file; and it fails here 
https://chromium.googlesource.com/chromium/src/+/b4600574aa6560a15f1d891f044af7a521141a01/ui/base/resource/data_pack.cc#278
Extracting the "corrupted" file using our script works correctly. So for me, we just need to figure out what we do miss during the writing part. It must be some bits used to save info about the aliases 
@wa4557 Do you think that you have some free time to take a look at this?

**Comment by wa4557** [comment]
I'll try and have a look

**Comment by varlesh** [comment]
@bil-elmoussaoui Maybe now delete chrome from database? Because after hardcode-tray Chrome not start anymore...

**Comment by bil-elmoussaoui** [comment]
You can add google-chrome and chromium to the blacklist until it's fixed

**Comment by arifcatalyst** [comment]
Any updates ?

**Comment by bil-elmoussaoui** [comment]
Sorry guys but I'm really busy those days with studies. I don't really have time to work on any issue at the moment. The latest commits were to add or update some app supports which doesn't take more than 5 minutes to do thanks to our simple database files. I will try to make some time for this as soon as possible.

**Comment by bil-elmoussaoui** [comment]
Fixed on master. I'm going to create a new release this evening or tomorrow. Can anybody try the master branch and see if it works as expected for you too?
It's working for me here with the latest Google Chrome/Chromium stable version
![screenshot from 2017-12-20 13-08-42](https://user-images.githubusercontent.com/7660997/34206466-f1c1e2aa-e586-11e7-9dc4-bb53820950c0.png)
PS: That was the gift i give you for the 300 :star:

**Comment by r4dixx** [comment]
Awesome! Thanks a ton for your work 🙂 I can try tonight

**Comment by arifcatalyst** [comment]
@bil-elmoussaoui It's not working for me. Using dev version of Chromium.

**Comment by bil-elmoussaoui** [comment]
It's not the same issue. But i have added chromium support few seconds ago. Can you try again using the latest master?

**Comment by bil-elmoussaoui** [comment]
It's still the v4.1 I will release the new version when this issue is marked as fixed

**Comment by arifcatalyst** [comment]
> It's not the same issue. But i have added chromium support few seconds ago. Can you try again using the latest master?
Not Working

**Comment by bil-elmoussaoui** [comment]
@arifcatalyst by not working, you mean that chromium doesn't even open for you? Or just the tray icon is not replaced?

**Comment by arifcatalyst** [comment]
Tray-icon is not replaced.

**Comment by bil-elmoussaoui** [comment]
Well, it's not the same issue at all. Can you please open a new issue for that instead? With the chromium verison and the resources.pak file that can be found in /usr/lib/chromium-dev/

**Comment by arifcatalyst** [comment]
How is it not ? 

>  Expected behavior and actual behavior
> Change tray icon to appropriate theme icon

Here is the `resources.pak` file 
[resources.pak.zip](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1576147/resources.pak.zip)

**Comment by bil-elmoussaoui** [comment]
Well, this issue was more of chrome not being able to run at all after applying hardcode tray. I will take a look this evening

**Comment by bil-elmoussaoui** [comment]
@arifcatalyst Should be fixed now.

**Comment by arifcatalyst** [comment]
Yes  it's now 

![screenshot_2017-12-20_23-20-47](https://user-images.githubusercontent.com/26674272/34221201-2cb0d1a4-e5dd-11e7-88d8-34d4fc32d14a.png)

**Comment by bil-elmoussaoui** [comment]
What are those two unthemed tray icons? :)

**Comment by arifcatalyst** [comment]
Albert and flux-gui

**Comment by GUiHKX** [comment]
Wohoo! Working fine on XFCE as well. Thanks!

![screenshot_2017-12-20_16-09-07](https://user-images.githubusercontent.com/626206/34221743-4cfd0ee2-e5a0-11e7-94d4-75ccd8facfa0.png)

**Comment by bil-elmoussaoui** [comment]
@GUiHKX I think that RSS icon can be fixed too ;)

**Comment by GUiHKX** [comment]
It's [QuiteRSS](https://github.com/QuiteRSS/quiterss), do you think it can be done?

**Comment by bil-elmoussaoui** [comment]
@GUiHKX The icon seems to be hardcoded on using the qrc assets files. See this line of code
https://github.com/QuiteRSS/quiterss/blob/d5a64fd2c6e037cf708fdaf895f34c2429813893/src/application/mainwindow.cpp#L642

They must replace that with loading the tray icon from the theme with a different icon name than the one they use right now (they can fallback to the current implementation if the icon is not found). I can provide a PR if they are okay with that; if you ever open an issue about it, let me know!

**Comment by GUiHKX** [comment]
Awesome! I'll try to open a ticket tomorrow, but it seems to me that the dev has been ignoring tickets lately. Anyway it's worth trying. Thanks

**Comment by orschiro** [comment]
> @arifcatalyst Should be fixed now.

@bil-elmoussaoui I am still having this problem. Ran hardcode-tray and then Google Chrome stable is no longer launching:

```
orschiro@x230 ~ $ google-chrome
[1:1:0124/085835.664612:ERROR:data_pack.cc(278)] Data pack file corruption: Alias #0 past end.
[1:1:0124/085835.664700:ERROR:resource_bundle.cc(810)] Failed to load /opt/google/chrome/resources.pak
Some features may not be available.
[3537:3537:0124/085835.830089:ERROR:data_pack.cc(278)] Data pack file corruption: Alias #0 past end.
[3537:3537:0124/085835.830162:ERROR:resource_bundle.cc(810)] Failed to load /opt/google/chrome/resources.pak
Some features may not be available.
--2018-01-24 08:58:36--  https://clients2.google.com/cr/report
Resolving clients2.google.com (clients2.google.com)... 216.58.210.142, 2a00:1450:4003:807::200e
Connecting to clients2.google.com (clients2.google.com)|216.58.210.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/fd/4’

Crash dump id: 4f2c451b7ca48dee
Segmentation fault (core dumped)
```

I need to reinstall the deb file to run Chrome again.

**Comment by bil-elmoussaoui** [comment]
Please update to the latest stable version

**Comment by orschiro** [comment]
This is the latest I can install:

```
orschiro@x230 ~ $ sudo add-apt-repository ppa:andreas-angerer89/sni-qt-patched
[sudo] password for orschiro: 
You are about to add the following PPA:
 This ppa contains git version from hardcode-tray, an app that allows theming hardcoded tray icons in Linux
Shipped is also a patched version of sni-qt necessary to fix hardcoded tray icons for apps that use sni-qt
 More info: https://launchpad.net/~andreas-angerer89/+archive/ubuntu/sni-qt-patched
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/tmp.7nATt8ATqU/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv-keys
8EC2D535
gpg: requesting key 8EC2D535 from hkp server keyserver.ubuntu.com
gpg: key 8EC2D535: "Launchpad PPA for Andreas Angerer" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
orschiro@x230 ~ $ sudo apt update
Hit:1 http://ppa.launchpad.net/andreas-angerer89/sni-qt-patched/ubuntu xenial InRelease
Hit:2 http://archive.canonical.com/ubuntu xenial InRelease                     
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Ign:4 http://ftp-stud.hs-esslingen.de/pub/Mirrors/packages.linuxmint.com sylvia InRelease
Hit:5 http://ftp.stw-bonn.de/ubuntu xenial InRelease                           
Hit:6 http://ftp-stud.hs-esslingen.de/pub/Mirrors/packages.linuxmint.com sylvia Release
Ign:7 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:8 http://ppa.launchpad.net/atareao/telegram/ubuntu xenial InRelease        
Hit:9 https://repo.skype.com/deb stable InRelease                              
Hit:10 http://ftp.stw-bonn.de/ubuntu xenial-updates InRelease                  
Hit:11 http://ftp.stw-bonn.de/ubuntu xenial-backports InRelease                
Hit:12 http://ppa.launchpad.net/numix/ppa/ubuntu xenial InRelease              
Hit:13 http://dl.google.com/linux/chrome/deb stable Release             
Hit:15 http://ppa.launchpad.net/otto-kesselgulasch/gimp/ubuntu xenial InRelease
Hit:16 http://ppa.launchpad.net/snwh/pulp/ubuntu xenial InRelease
Hit:17 http://ppa.launchpad.net/ubuntuhandbook1/audacity/ubuntu xenial InRelease
Get:18 http://security.ubuntu.com/ubuntu xenial-security/main amd64 DEP-11 Metadata [62,7 kB]
Get:19 http://security.ubuntu.com/ubuntu xenial-security/main DEP-11 64x64 Icons [66,2 kB]
Get:21 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 DEP-11 Metadata [51,3 kB]
Get:22 http://security.ubuntu.com/ubuntu xenial-security/universe DEP-11 64x64 Icons [85,1 kB]
Hit:23 http://ppa.launchpad.net/webupd8team/y-ppa-manager/ubuntu xenial InRelease
Fetched 368 kB in 1s (367 kB/s)                                                
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
orschiro@x230 ~ $ sudo apt install sni-qt sni-qt:i386 hardcode-tray
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sni-qt is already the newest version (0.2.7+20161212~11~ubuntu16.04.1).
hardcode-tray is already the newest version (3.5.2.1~885~ubuntu16.04.1).
sni-qt:i386 is already the newest version (0.2.7+20161212~11~ubuntu16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by iwex** [comment]
@bil-elmoussaoui [ERROR] 2018-02-15 13:44:04 Couldn't find a PNG file. :)
Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by bil-elmoussaoui** [comment]
@iwex can you please open a new issue with the requested information in the issue template? Its a completely different issue...
