### ISSUE TITLE
Chrome makes script impossible to use

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#75]
This happens when using the script with google-chrome :(
![bildschirmfoto vom 2015-07-18 13 49 38](https://cloud.githubusercontent.com/assets/6475757/8893582/29ec5610-3396-11e5-8b7d-cf1d5b4a6acf.png)

There seems to be an issue with the js script...

**Comment by Foggalong** [comment]
Just maybe :P

**Comment by bil-elmoussaoui** [comment]
:S I Will test this right now.. The new indicator icon is working?

**Comment by wa4557** [comment]
I don't know I've never had a chrome icon in the tray

**Comment by Foggalong** [comment]
I've just noticed how massive your tray is O.o

**Comment by bil-elmoussaoui** [comment]
@wa4557 Can you try this to see if it's working ? [System Tray icons not showing [closed]](http://askubuntu.com/questions/447739/system-tray-icons-not-showing)

**Comment by wa4557** [comment]
@Foggalong and it looks great with Numix. The funny thing I use each and every one of those appindicators
@bil-elmoussaoui No that's not it, I just don't know how I can trigger a notification in chrome so that it shows up ...

**Comment by bil-elmoussaoui** [comment]
The icon names are not the same in every Chrome version; i installed the latest version and look what i've got 
![screenshot 26-07-2015 13 24 24](https://cloud.githubusercontent.com/assets/7660997/8893663/2cc0fb26-339a-11e5-805e-f239364a4570.png)

In my case, the icon names are 7353,7354, 7355 and 7356. Can you confirm that?

**Comment by bil-elmoussaoui** [comment]
To fix the issue in your case, restore the old chrome_pak file and change the icon names in the database file and run the script again

**Comment by wa4557** [comment]
Confirmed that changing the icons to the correct one did fix that issue. But since chrome is updated quite regularly it seems to me that we need to do something else here :(

**Comment by bil-elmoussaoui** [comment]
As the icons are still the same; maybe a way to check every icon file content with the default one that we will include in the script if we can. What do you think?

**Comment by wa4557** [comment]
That's actually a brilliant idea, but how to check a the content of a png icon?

**Comment by bil-elmoussaoui** [comment]
I think that we will need a new way to get the right icon names for chrome, we can copy the png icons and put them in a new folder? and then check every png icon file in the extracted folder to get the right icon names. If the design changed we will have just to add the new icons to the icon folder. I can do that this weekend

**Comment by bil-elmoussaoui** [comment]
and to compare the images files, we can use something like that : http://blog.iconfinder.com/detecting-duplicate-images-using-python/

**Comment by bil-elmoussaoui** [comment]
I have a part of the final solution : 
```python
def get_real_chrome_icons():
    icons_folder = icons_folder + "/chrome"
    extracted_chrome_dir = "/extracted"
    default_icons = ["google-chrome-notification",
            "google-chrome-notification-disabled",
            "google-chrome-no-notification",
            "google-chrome-no-notification-disabled"]
    list_icons = {}
    for icon in listdir(extracted_chrome_dir):
        if path.isfile(icon):
            if get_extension(icon) and get_extension(icon) == "png":
            for default_icon in default_icons:
                default_content = open(icons_folder + default_icon + ".png").read()
                lookup_content = open(extracted_chrome_dir + icon).read()
                if md5(default_content).hexdigest() == md5(lookup_content).hexdigest():
                    list_icons[default_icon] = icon
        return list_icons 
```
the default icons will be copied from my version of Chrome to /database/icons/chrome
and this part of code is added to ```get_app_icons(app_name)``` 
```python
        if app_name == "google-chrome":
            real_icons = get_real_chrome_icons()
            for new_icon in real_icons:
                for old_icon in icons:
                    if old_icon[1] == new_icon:
                        icons[0] = real_icons[new_icon]
```
the last issue is how to extract the google chrome pak file :P Should i use ```subprocess.call``` ?

**Comment by wa4557** [comment]
I like that solution,  but you'd probably better use `subprocess.Popen` because it enables to speak with the subprocess when necessary (and catch error messages for example)

**Comment by bil-elmoussaoui** [comment]
Well i did everything and everything should work fine expect one issue  when i do call the node-chrome-pak file i have this error 
`
(b'', b'') (b'', b"\nmodule.js:340\n    throw err;\n          ^\nError: Cannot find module '/home/bilal/Github/Hardcode-Tray/database/scripts/node-chrome-pak.js '\n    at Function.Module._resolveFilename (module.js:338:15)\n    at Function.Module._load (module.js:280:25)\n    at Function.Module.runMain (module.js:497:10)\n    at startup (node.js:119:16)\n    at node.js:902:3\n")
`
my python code is 
`
def get_real_chrome_icons(chrome_link):
    images_dir = icons_folder + "/chrome"
    extracted_chrome_dir = "/tmp/extracted"
    default_icons = ["google-chrome-notification",
            "google-chrome-notification-disabled",
            "google-chrome-no-notification",
            "google-chrome-no-notification-disabled"]
    list_icons = {}
    p = Popen(["cp", chrome_link + "/chrome_100_percent.pak", "/tmp/chrome_100_percent_old.pak"], stdout=PIPE, stderr=PIPE)
    r = Popen(["node", db_folder + "/" + script_folder + "/node-chrome-pak.js " , "unpack", "/tmp/chrome_100_percent_old.pak"], stdout=PIPE, stderr=PIPE)
    print(p.communicate() , r.communicate()) # show error
    for icon in listdir(extracted_chrome_dir):
        if path.isfile(icon):
            if get_extension(icon) and get_extension(icon) == "png":
                for default_icon in default_icons:
                    default_content = open(images_dir + default_icon + ".png").read()
                    lookup_content = open(extracted_chrome_dir + icon).read()
                    if md5(default_content).hexdigest() == md5(lookup_content).hexdigest():
                        list_icons[default_icon] = icon
        return list_icons 
`
i tried to create a new beta branch so you can test this but somehow something is not working here :P

**Comment by bil-elmoussaoui** [comment]
You can try the script on the beta branch https://github.com/bil-elmoussaoui/Hardcode-Tray/tree/beta

**Comment by wa4557** [comment]
Yeah it seems that the extracted folder is not in `tmp` but rather in `database/scripts`. Which means that the `extracted_chrome_dir` variable is wrong. If you change that to `database/scripts` (which is also OK i guess) it works

**Comment by bil-elmoussaoui** [comment]
I will give it a try ;)

**Comment by bil-elmoussaoui** [comment]
Fixed in my latest commit :P

**Comment by wa4557** [comment]
Nope still the same red areas :(

**Comment by bil-elmoussaoui** [comment]
are you sure ? restore the pak file and try again :/ i tested this for like 2 hours

**Comment by wa4557** [comment]
unfortunately yes. I guess the problem is, that the `.extracted` folder is not deleted after image comparison?

**Comment by bil-elmoussaoui** [comment]
Well, i dont think it's a problem :/ have You reinstalled chrome as the bak file might be damaged as well.
i will modify the code later to remove the extracted folder

**Comment by wa4557** [comment]
Yes. I'll try it a little bit later, it's too hot here right now :)

**Comment by wa4557** [comment]
Ok the problem is not your code but rather the javascript code. Even if I don't change anything just unpack and then pack again the error occurs. Unfortunately I can't code javascript :(

**Comment by bil-elmoussaoui** [comment]
i didnt try chrome, but only if the icons changes; i will take a look later if there's a newer version of the script. Is there an other way to modify pak files ?

**Comment by wa4557** [comment]
The icon change works, I can confirm that.
The script doesn't. I tried to look into the script but my javascript knowledge is too bad in order to get some meaningful insights. There seems to be some python code that does exactly what we are looking for but I don't know if that one works: http://askubuntu.com/questions/470691/how-can-i-replace-google-chromes-low-resolution-notification-icon

**Comment by wa4557** [comment]
I almost have this python script (from my above comment, slightly modified) ready. This one seems to work better than the javascript one

**Comment by bil-elmoussaoui** [comment]
have you tested this to pack the extracted folder ? if yes, is this fixing the red background issue?

**Comment by wa4557** [comment]
I have tested it yes, and it is fixing the red background issue. It just needs a bit rewriting

**Comment by bil-elmoussaoui** [comment]
so good! i took a look in how to fix the chrome/chromuim indicator and it's seems that those icons are in the same pak file. so fixing this will fix the other issue too ;) and the code i pushed later need some cleaning too.

**Comment by wa4557** [comment]
Cool! I'm still facing a bug I don't know how to fix, but as soon as this is finished I'll open a PR :)
